[package]
name = "chatgpt-analyzer"
version = "0.1.0"
edition = "2024"

[dependencies]
prompted = "0.2.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.141"
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = "0.29.0"
chrono = "0.4.41"
url = "2.5.4"
